apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cicd-project.fullname" . }}-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ template "cicd-project.fullname" . }}-web
  template:
    metadata:
      labels:
        app: {{ template "cicd-project.fullname" . }}-web
    spec:
      initContainers:
        - name: migrate
          image: martinkozle/cicd-project-sqlx:latest
          command: ["sqlx", "database", "create", ";", "sqlx", "migrate", "run"]
          env:
          - name: DATABASE_URL
            value: {{ template "cicd-project.databaseUrl" . }}
      containers:
        - name: web
          image: {{ .Values.image.repository }}:{{ .Values.web.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: {{ template "cicd-project.databaseUrl" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cicd-project.fullname" . }}-db
spec:
  selector:
    matchLabels:
      app: {{ template "cicd-project.fullname" . }}-db
  template:
    metadata:
      labels:
        app: {{ template "cicd-project.fullname" . }}-db
    spec:
      containers:
      - name: db
        image: postgres:15
        env:
        - name: POSTGRES_PASSWORD
          value: {{ .Values.env.POSTGRES_PASSWORD }}
        - name: POSTGRES_USER
          value: {{ .Values.env.POSTGRES_USER }}
        - name: POSTGRES_DB
          value: {{ .Values.env.POSTGRES_DB }}
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: {{ template "cicd-project.fullname" . }}-db-pvc
