apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "cicd-project.fullname" . }}-web
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "cicd-project.fullname" . }}-web
            port:
              name: http
