apiVersion: v1
kind: Service
metadata:
  name: {{ template "cicd-project.fullname" . }}-db
spec:
  selector:
    app: {{ template "cicd-project.fullname" . }}-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
