apiVersion: v1
kind: Service
metadata:
  name: {{ template "cicd-project.fullname" . }}-web
spec:
  selector:
    app: {{ template "cicd-project.fullname" . }}-web
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: NodePort
