name: Docker Build, Test, Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Test
        run: docker build -t ${{ github.repository }}_test .
      - name: Test
        run: docker run ${{ github.repository }}_test
      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build Publish
        if: github.event_name == 'push'
        run: docker build -t ${{ github.repository }} .
      - name: Publish
        if: github.event_name == 'push'
        run: docker push ${{ github.repository }}
